# Problem 4.1
Consider the game with matrix $A$. Past experience in playing the game with player **II** enables player **I** to arrive at a set of probabilities reflecting his belief of the column that **II** will choose. **I** thinks that with probabilities 1/5, 1/5, 1/5, and 2/5, **II** will choose colums 1, 2, 3, and 4 respectively.

$$A = \begin{pmatrix} 0 &7 & 2 & 4 \\ 1 & 4 & 8 & 2\\ 9 & 3 & -1 & 6 \end{pmatrix}$$

 * Find for **I** a Bayes strategy (best response) against (1/5, 1/5, 1/5, 2/5).
 * Suppose **II** guesses correctly that **I** is going to use a Bayes strategy against (1/5,1/5,1/5,2/5). Instruct **II** on the strategy she should use - that is, find **II**'s Bayes strategy against **I**'s Bayes strategy against 1/5,1/5,1/5,2/5.

*Solution:* The principle of indifference means that there is a pure strategy for player **I** that is a bayes strategy. We calculate the average payoff when **I** plays row *i* against **II** as $a_i:$

In [2]:
import numpy as np
A = np.array([[0,7,2,4],[1,4,8,2],[9,3,-1,6]])
q = np.array([[1/5],[1/5],[1/5],[2/5]])

np.matmul(A,q)

array([[3.4],
       [3.4],
       [4.6]])

Thus, **I** will play row 3.

In this  case, **II** will play column 3, since it is the smallest of the payoffs (least loss) in the column.

# Problem 4.2

The game with matrix $A$ has value zero, and $(6/11,3/11,2/11)$ is optimal for $I$.

$$A = \begin{pmatrix} 0 & -1 & 1 \\ 2 & 0 & -2 \\ -3 & 3 &0 \end{pmatrix} \qquad B = \begin{pmatrix} 5 & 3 & 7 \\ 9 & 5 & 1 \\ -1 & 11 & 5 \end{pmatrix}$$

 * Find the value of the game with matrix $B$ and an optimal strategy for *I*
 * Find an optimal strategy for **II** in both games
 
 

*Solution:*

In [3]:
A = np.array([[0,-1,1],[2,0,-2],[-3,3,0]])
B = np.array([[5,3,7],[9,5,1],[-1,11,5]])

In [7]:
A*2+5 == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Hence, by lemma 3, the value of the game with matrix $B$ is 5, and $p = (6/11,3/11,2/11)$

In [9]:
p = np.array([[6/11,3/11,2/11]])
np.matmul(p,A)

array([[0., 0., 0.]])

Since this gives 0 in all cases, any column in equal probability gives an optimal strategy for $II$; i.e., $q = (1/3,1/3,1/3)$.

# Problem 4.4:

Use the method presented in section 4.5 to solve the game with matrix $$A = \begin{pmatrix} 0 & 1 2 \\ 2 & -1 & -2  \\ 3 & -3 & 0 \end{pmartix}.$$

*Solution:*

Following the pivot method, we get $$v = 1/2, p=(3/4,1/4,0), q= (1/2,1/2,0).$$